services:
    web:
        build:
            context: .
            dockerfile: ./apps/web/Dockerfile
        environment:
            - LOG_LEVEL=debug
            - API=http://api:1993
        ports:
            - 3000:3000
        depends_on:
            - api

    api:
        build:
            context: .
            dockerfile: ./apps/api/Dockerfile
        secrets:
            - db-password
        environment:
            - LOG_LEVEL=debug
            - DB_HOST=db
            - DB_PASSWORD_FILE=/run/secrets/db-password
        ports:
            - 1993:1993
        depends_on:
            - db

    db:
        image: postgres:17-alpine
        ports:
            - 5432:5432
        secrets:
            - db-password
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
            - POSTGRES_USER=karr
            - POSTGRES_DB=karr
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U karr"]
            interval: 5s
            timeout: 5s
            retries: 5

    caddy:
        build:
            context: ./apps/caddy
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8080:8080"
            #- "443:443"
            #- "443:443/udp"
        environment:
            - TZ=Europe/Paris
            - HOST=localhost:8080
            - API_PORT=1993
            - CADDY_DISABLE_TLS=1
        volumes:
            - caddy_data:/data
            - caddy_config:/config

volumes:
    caddy_data:
    caddy_config:

secrets:
    db-password:
        file: ./pass.txt
