name: karr

# Reverse Proxy is not included, this assumes the auth server is running separately.

services:
    web:
        image: ghcr.io/karr-mobi/karr-web:latest
        networks:
            - karr_network
        secrets:
            - db-password
        ports:
            - "3555:3000"
        environment:
            - LOG_LEVEL=debug
            - DB_USER=karr
            - DB_HOST=db
            - DB_PASSWORD_FILE=/run/secrets/db-password
            - PORT=3000
        volumes:
            - /srv/http/karr/karr.config.yaml:/app/config/karr.config.yaml
        depends_on:
            - db

    db:
        image: postgres:17-alpine
        networks:
            - karr_network
        secrets:
            - db-password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
            - POSTGRES_USER=karr
            - POSTGRES_DB=karr
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U karr"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:

networks:
    karr_network:

secrets:
    db-password:
        file: /srv/http/karr/pass.txt
