packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  web:
    '@tanstack/react-form': ^1.12.3
    '@tanstack/react-query': ^5.81.2
    babel-plugin-react-compiler: ^19.1.0-rc.2
    next: ^15.3.3
    next-themes: ^0.4.6
    next-intl: ^4.1.0
    posthog-js: ^1.253.4
    react: ^19.1.0
    react-dom: ^19.1.0
  api:
    '@hono/zod-validator': ^0.5.0
    '@openauthjs/openauth': ^0.4.3
    db0: ^0.3.2
    drizzle-kit: ^0.31.1
    drizzle-orm: ^0.43.1
    drizzle-zod: ^0.8.2
    hono: ^4.8.2
    postgres: ^3.4.7
    resend: ^4.6.0
    srvx: ^0.7.5
    unstorage: ^1.16.0
  docs:
    '@astrojs/starlight': ^0.34.4
    '@astrojs/starlight-tailwind': ^4.0.1
    '@deno/astro-adapter': ^0.3.1
    astro: ^5.10.0
    starlight-sidebar-topics: ^0.6.0
  utils:
    '@std/text': jsr:^1.0.14
    confbox: ^0.2.2
    defu: ^6.1.4
    esbuild: ^0.25.5
    neverthrow: ^8.2.0
    ofetch: ^1.4.1
    std-env: ^3.9.0
    tinyrainbow: ^2.0.0
    unplugin: ^2.3.5
    sharp: ^0.34.2
    zod: ^3.25.67
  ui:
    '@icons-pack/react-simple-icons': ^12.9.0
    '@hookform/resolvers': ^5.1.1
    '@tailwindcss/postcss': ^4.1.10
    '@tailwindcss/vite': ^4.1.10
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    date-fns: ^4.1.0
    lucide-react: ^0.507.0
    motion: ^12.18.1
    react-day-picker: ^9.7.0
    react-hook-form: ^7.58.1
    react-intersection-observer: ^9.16.0
    sonner: ^2.0.5
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.10
    tailwindcss-animate: ^1.0.7
  radix:
    '@radix-ui/react-accordion': ^1.2.11
    '@radix-ui/react-alert-dialog': ^1.1.14
    '@radix-ui/react-aspect-ratio': ^1.1.7
    '@radix-ui/react-avatar': ^1.1.10
    '@radix-ui/react-checkbox': ^1.3.2
    '@radix-ui/react-collapsible': ^1.1.11
    '@radix-ui/react-context-menu': ^2.2.15
    '@radix-ui/react-dialog': ^1.1.14
    '@radix-ui/react-dropdown-menu': ^2.1.15
    '@radix-ui/react-hover-card': ^1.1.14
    '@radix-ui/react-label': ^2.1.7
    '@radix-ui/react-menubar': ^1.1.15
    '@radix-ui/react-navigation-menu': ^1.2.13
    '@radix-ui/react-popover': ^1.1.14
    '@radix-ui/react-progress': ^1.1.7
    '@radix-ui/react-radio-group': ^1.3.7
    '@radix-ui/react-scroll-area': ^1.2.9
    '@radix-ui/react-select': ^2.2.5
    '@radix-ui/react-separator': ^1.1.7
    '@radix-ui/react-slider': ^1.3.5
    '@radix-ui/react-slot': ^1.2.3
    '@radix-ui/react-switch': ^1.2.5
    '@radix-ui/react-tabs': ^1.1.12
    '@radix-ui/react-toast': ^1.2.14
    '@radix-ui/react-toggle': ^1.1.9
    '@radix-ui/react-toggle-group': ^1.1.10
    '@radix-ui/react-tooltip': ^1.2.7
  types:
    '@types/node': ^22.15.32
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
  test:
    vitest: ^3.2.4
    vite-tsconfig-paths: ^5.1.4
  lint:
    '@biomejs/biome': 2.0.0
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@eslint/js': ^9.29.0
    '@next/eslint-plugin-next': ^15.3.4
    '@tanstack/eslint-plugin-query': ^5.81.2
    '@typescript-eslint/eslint-plugin': ^8.34.1
    '@typescript-eslint/parser': ^8.34.1
    eslint: ^9.29.0
    eslint-config-biome: ^1.9.4
    eslint-config-prettier: ^10.1.5
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-turbo: ^2.5.4
    lint-staged: ^15.5.2
    typescript-eslint: ^8.34.1
  devtools:
    '@turbo/gen': ^2.5.4
    changelogen: ^0.6.1
    eslint-plugin-pnpm: ^0.3.1
    globals: ^16.2.0
    husky: ^9.1.7
    taze: ^19.1.0
    turbo: ^2.5.4
    tsx: ^4.20.3
    typescript: ^5.8.3

disallowWorkspaceCycles: true

overrides:
  next>safe-buffer: npm:@socketregistry/safe-buffer@1.0.7

preferFrozenLockfile: true
