packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  api:
    "@hono/zod-validator": ^0.5.0
    "@libs/xml": jsr:^7.0.0
    "@openauthjs/openauth": ^0.4.3
    "@orpc/contract": ^1.9.3
    "@orpc/server": ^1.9.3
    db0: ^0.3.4
    drizzle-kit: ^0.31.5
    drizzle-orm: ^0.43.1
    drizzle-zod: ^0.8.3
    hono: ^4.10.3
    postgres: ^3.4.7
    resend: ^4.8.0
    srvx: ^0.7.5
    unstorage: ^1.17.1
  devtools:
    "@turbo/gen": ^2.5.8
    changelogen: ^0.6.2
    eslint-plugin-pnpm: ^0.3.1
    globals: ^16.4.0
    husky: ^9.1.7
    prettier: ^3.6.2
    rolldown: ^1.0.0-beta.43
    taze: ^19.7.0
    tsdown: ^0.13.5
    tsx: ^4.20.6
    turbo: ^2.5.8
    typescript: ^5.9.3
  docs:
    "@astrojs/starlight": ^0.35.3
    "@astrojs/starlight-tailwind": ^4.0.1
    "@deno/astro-adapter": ^0.3.2
    astro: ^5.14.4
    starlight-sidebar-topics: ^0.6.1
  lint:
    "@biomejs/biome": 2.0.0
    "@commitlint/cli": ^19.8.1
    "@commitlint/config-conventional": ^19.8.1
    "@eslint/js": ^9.37.0
    "@next/eslint-plugin-next": ^15.5.4
    "@tanstack/eslint-plugin-query": ^5.91.0
    "@typescript-eslint/eslint-plugin": ^8.46.0
    "@typescript-eslint/parser": ^8.46.0
    eslint: ^9.37.0
    eslint-config-biome: ^1.9.4
    eslint-config-prettier: ^10.1.8
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-turbo: ^2.5.8
    lint-staged: ^15.5.2
    typescript-eslint: ^8.46.0
  radix:
    "@radix-ui/react-accordion": ^1.2.12
    "@radix-ui/react-alert-dialog": ^1.1.15
    "@radix-ui/react-aspect-ratio": ^1.1.7
    "@radix-ui/react-avatar": ^1.1.10
    "@radix-ui/react-checkbox": ^1.3.3
    "@radix-ui/react-collapsible": ^1.1.12
    "@radix-ui/react-context-menu": ^2.2.16
    "@radix-ui/react-dialog": 1.1.15
    "@radix-ui/react-dropdown-menu": ^2.1.16
    "@radix-ui/react-hover-card": ^1.1.15
    "@radix-ui/react-label": ^2.1.7
    "@radix-ui/react-menubar": ^1.1.16
    "@radix-ui/react-navigation-menu": ^1.2.14
    "@radix-ui/react-popover": ^1.1.15
    "@radix-ui/react-progress": ^1.1.7
    "@radix-ui/react-radio-group": ^1.3.8
    "@radix-ui/react-scroll-area": ^1.2.10
    "@radix-ui/react-select": ^2.2.6
    "@radix-ui/react-separator": ^1.1.7
    "@radix-ui/react-slider": ^1.3.6
    "@radix-ui/react-slot": ^1.2.3
    "@radix-ui/react-switch": ^1.2.6
    "@radix-ui/react-tabs": ^1.1.13
    "@radix-ui/react-toast": ^1.2.15
    "@radix-ui/react-toggle": ^1.1.10
    "@radix-ui/react-toggle-group": ^1.1.11
    "@radix-ui/react-tooltip": ^1.2.8
  test:
    vite-tsconfig-paths: ^5.1.4
    vitest: ^3.2.4
  types:
    "@types/node": ^22.18.10
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.1
  ui:
    "@hookform/resolvers": ^5.2.2
    "@icons-pack/react-simple-icons": ^12.9.0
    "@tailwindcss/postcss": ^4.1.14
    "@tailwindcss/vite": ^4.1.14
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    date-fns: ^4.1.0
    lucide-react: ^0.507.0
    motion: ^12.23.24
    react-day-picker: ^9.11.1
    react-hook-form: ^7.65.0
    react-intersection-observer: ^9.16.0
    sonner: ^2.0.7
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.14
    tailwindcss-animate: ^1.0.7
    vaul: ^1.1.2
  utils:
    "@std/text": jsr:^1.0.16
    confbox: ^0.2.2
    defu: ^6.1.4
    esbuild: ^0.25.10
    neverthrow: ^8.2.0
    ofetch: ^1.4.1
    pino: ^9.13.1
    pino-pretty: ^13.1.2
    sharp: ^0.34.4
    std-env: ^3.9.0
    tinyrainbow: ^2.0.0
    unplugin: ^2.3.10
    zod: ^4.1.12
  web:
    "@orpc/client": ^1.9.3
    "@orpc/tanstack-query": ^1.9.3
    "@tanstack/react-form": ^1.23.7
    "@tanstack/react-query": ^5.90.2
    babel-plugin-react-compiler: ^19.1.0-rc.3
    next: ^15.5.4
    next-intl: ^4.3.12
    next-themes: ^0.4.6
    nuqs: ^2.7.1
    posthog-js: ^1.275.1
    react: ^19.2.0
    react-dom: ^19.2.0
  mail:
    "@react-email/components": ^0.5.6
    "@react-email/preview-server": ^4.3.0
    react-email: ^4.3.0

disallowWorkspaceCycles: true

overrides:
  next>safe-buffer: npm:@socketregistry/safe-buffer@1.0.7

preferFrozenLockfile: true
