packages:
    - apps/*
    - packages/*
    - tooling/*

catalog:
    "@types/node": ^22.13.10
    "@types/react": 19.0.10
    "@types/react-dom": 19.0.4
    confbox: ^0.2.1
    tinyrainbow: ^2.0.0

    # Web packages
    "@hookform/resolvers": ^4.1.3
    "@ory/client": ^1.18.5
    "@ory/integrations": ^1.3.1
    "@oslojs/crypto": ^1.0.1
    "@oslojs/jwt": ^0.3.0
    "@oslojs/webauthn": ^1.0.0
    "@radix-ui/react-checkbox": ^1.1.4
    "@radix-ui/react-dropdown-menu": ^2.1.6
    "@radix-ui/react-label": ^2.1.2
    "@radix-ui/react-popover": ^1.1.6
    "@radix-ui/react-separator": ^1.1.2
    "@radix-ui/react-slot": ^1.1.2
    "@radix-ui/react-select": ^2.1.6
    "@radix-ui/react-tabs": ^1.1.3
    "@tailwindcss/postcss": 4.0.14
    "@tanstack/react-query": ^5.68.0
    babel-plugin-react-compiler: 19.0.0-beta-decd7b8-20250118
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    date-fns: ^4.1.0
    framer-motion: ^12.5.0
    lucide-react: ^0.482.0
    next: ^15.2.2
    next-themes: ^0.4.6
    next-intl: ^4.0.2
    ofetch: ^1.4.1
    posthog-js: ^1.231.0
    react: ^19.0.0
    react-dom: ^19.0.0
    react-day-picker: ^9.6.2
    react-hook-form: ^7.54.2
    sonner: ^2.0.1
    tailwindcss: 4.0.14
    tailwindcss-animate: ^1.0.7
    tailwind-merge: ^3.0.2
    ua-parser-js: ^2.0.3
    zod: ^3.24.2

    # API packages
    "@hono/node-server": ^1.13.8
    drizzle-kit: ^0.30.5
    drizzle-orm: ^0.40.0
    drizzle-zod: ^0.6.1
    esbuild: ^0.25.1
    hono: ^4.7.4
    neverthrow: ^8.2.0
    postgres: ^3.4.5

catalogs:
    tooling:
        "@commitlint/cli": ^19.8.0
        "@commitlint/config-conventional": ^19.8.0
        "@eslint/js": ^9.22.0
        "@ianvs/prettier-plugin-sort-imports": ^4.4.1
        "@next/eslint-plugin-next": ^15.2.2
        "@tanstack/eslint-plugin-query": ^5.68.0
        "@turbo/gen": ^2.4.4

        "@typescript-eslint/eslint-plugin": ^8.26.1
        "@typescript-eslint/parser": ^8.26.1
        changelogen: ^0.6.1
        eslint: ^9.22.0
        eslint-config-prettier: ^10.1.1
        eslint-plugin-react: ^7.37.4
        eslint-plugin-react-hooks: ^5.2.0
        eslint-plugin-turbo: ^2.4.4
        globals: ^16.0.0
        husky: ^9.1.7
        lint-staged: ^15.5.0
        prettier: ^3.5.3
        prettier-plugin-tailwindcss: ^0.6.11
        turbo: ^2.4.4
        tsx: ^4.19.3
        typescript: ^5.8.2
        typescript-eslint: ^8.26.1

    vitest:
        vitest: ^3.0.8
        vite-tsconfig-paths: 5.1.4
