disallowWorkspaceCycles: true

packages:
    - apps/*
    - packages/*
    - tooling/*

catalog:
    "@types/node": ^22.15.3
    "@types/react": 19.0.10
    "@types/react-dom": 19.1.2
    confbox: ^0.2.1
    tinyrainbow: ^2.0.0

    # Web packages
    "@icons-pack/react-simple-icons": ^12.7.0
    "@hookform/resolvers": ^5.0.1
    "@radix-ui/react-accordion": 1.2.2
    "@radix-ui/react-alert-dialog": 1.1.4
    "@radix-ui/react-aspect-ratio": 1.1.1
    "@radix-ui/react-avatar": 1.1.2
    "@radix-ui/react-checkbox": 1.2.3
    "@radix-ui/react-collapsible": 1.1.2
    "@radix-ui/react-context-menu": 2.2.4
    "@radix-ui/react-dialog": 1.1.4
    "@radix-ui/react-dropdown-menu": ^2.1.6
    "@radix-ui/react-hover-card": 1.1.4
    "@radix-ui/react-label": ^2.1.2
    "@radix-ui/react-menubar": 1.1.4
    "@radix-ui/react-navigation-menu": 1.2.3
    "@radix-ui/react-popover": ^1.1.6
    "@radix-ui/react-progress": 1.1.1
    "@radix-ui/react-radio-group": 1.2.2
    "@radix-ui/react-scroll-area": 1.2.2
    "@radix-ui/react-select": ^2.2.2
    "@radix-ui/react-separator": ^1.1.2
    "@radix-ui/react-slider": 1.3.2
    "@radix-ui/react-slot": ^1.2.0
    "@radix-ui/react-switch": 1.1.2
    "@radix-ui/react-tabs": 1.1.2
    "@radix-ui/react-toast": 1.2.4
    "@radix-ui/react-toggle": 1.1.1
    "@radix-ui/react-toggle-group": 1.1.1
    "@radix-ui/react-tooltip": 1.1.6
    "@tailwindcss/postcss": 4.0.14
    "@tanstack/react-query": ^5.70.0
    babel-plugin-react-compiler: 19.0.0-beta-decd7b8-20250118
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    date-fns: ^4.1.0
    lucide-react: ^0.503.0
    motion: ^12.6.3
    next: ^15.3.0
    next-themes: ^0.4.6
    next-intl: ^4.0.3
    ofetch: ^1.4.1
    react: ^19.0.0
    react-dom: ^19.0.0
    react-day-picker: ^9.6.2
    react-hook-form: ^7.54.2
    react-intersection-observer: ^9.16.0
    sonner: ^2.0.1
    tailwind-merge: ^3.0.2
    tailwindcss: ^4.1.4
    tailwindcss-animate: ^1.0.7
    zod: next

    # API packages
    "@hono/node-server": ^1.14.0
    "@openauthjs/openauth": ^0.4.3
    db0: ^0.3.1
    drizzle-kit: ^0.30.5
    drizzle-orm: ^0.42.0
    drizzle-zod: ^0.7.1
    esbuild: ^0.25.2
    hono: ^4.7.4
    neverthrow: ^8.2.0
    postgres: ^3.4.5
    unstorage: ^1.15.0

catalogs:
    tooling:
        "@biomejs/biome": 1.9.4
        "@commitlint/cli": ^19.8.0
        "@commitlint/config-conventional": ^19.8.0
        "@eslint/js": ^9.25.1
        "@next/eslint-plugin-next": ^15.3.1
        "@tanstack/eslint-plugin-query": ^5.73.3
        "@turbo/gen": ^2.4.4
        "@typescript-eslint/eslint-plugin": ^8.31.0
        "@typescript-eslint/parser": ^8.30.1
        changelogen: ^0.6.1
        eslint: ^9.22.0
        eslint-config-prettier: ^10.1.1
        eslint-plugin-react: ^7.37.4
        eslint-plugin-react-hooks: ^5.2.0
        eslint-plugin-turbo: ^2.5.0
        globals: ^16.0.0
        husky: ^9.1.7
        lint-staged: ^15.5.0
        turbo: ^2.5.0
        tsx: ^4.19.3
        typescript: ^5.8.2
        typescript-eslint: ^8.28.0

    vitest:
        vitest: ^3.0.8
        vite-tsconfig-paths: 5.1.4
