disallowWorkspaceCycles: true
preferFrozenLockfile: true

packages:
  - apps/*
  - packages/*
  - tooling/*

catalogs:
  ## Direct dependencies
  web:
    "@tanstack/react-query": ^5.75.2
    babel-plugin-react-compiler: ^19.1.0-rc.1
    next: ^15.3.1
    next-themes: ^0.4.6
    next-intl: ^4.1.0
    posthog-js: ^1.239.1
    react: ^19.1.0
    react-dom: ^19.1.0

  api:
    "@hono/node-server": ^1.14.1
    "@openauthjs/openauth": ^0.4.3
    db0: ^0.3.2
    drizzle-kit: ^0.30.6
    drizzle-orm: ^0.42.0
    drizzle-zod: ^0.7.1
    hono: ^4.7.8
    postgres: ^3.4.5
    unstorage: ^1.16.0

  utils:
    confbox: ^0.2.2
    esbuild: ^0.25.3
    neverthrow: ^8.2.0
    ofetch: ^1.4.1
    tinyrainbow: ^2.0.0
    zod: next

  ui:
    "@icons-pack/react-simple-icons": ^12.7.0
    "@hookform/resolvers": ^5.0.1
    "@tailwindcss/postcss": ^4.1.5
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    date-fns: ^4.1.0
    lucide-react: ^0.503.0
    motion: ^12.9.4
    react-day-picker: ^9.6.7
    react-hook-form: ^7.56.2
    react-intersection-observer: ^9.16.0
    sonner: ^2.0.3
    tailwind-merge: ^3.2.0
    tailwindcss: ^4.1.5
    tailwindcss-animate: ^1.0.7

  radix:
    "@radix-ui/react-accordion": ^1.2.8
    "@radix-ui/react-alert-dialog": ^1.1.11
    "@radix-ui/react-aspect-ratio": ^1.1.4
    "@radix-ui/react-avatar": ^1.1.7
    "@radix-ui/react-checkbox": ^1.2.3
    "@radix-ui/react-collapsible": ^1.1.8
    "@radix-ui/react-context-menu": ^2.2.12
    "@radix-ui/react-dialog": ^1.1.11
    "@radix-ui/react-dropdown-menu": ^2.1.12
    "@radix-ui/react-hover-card": ^1.1.11
    "@radix-ui/react-label": ^2.1.4
    "@radix-ui/react-menubar": ^1.1.12
    "@radix-ui/react-navigation-menu": ^1.2.10
    "@radix-ui/react-popover": ^1.1.11
    "@radix-ui/react-progress": ^1.1.4
    "@radix-ui/react-radio-group": ^1.3.4
    "@radix-ui/react-scroll-area": ^1.2.6
    "@radix-ui/react-select": ^2.2.2
    "@radix-ui/react-separator": ^1.1.4
    "@radix-ui/react-slider": ^1.3.2
    "@radix-ui/react-slot": ^1.2.0
    "@radix-ui/react-switch": ^1.2.2
    "@radix-ui/react-tabs": ^1.1.9
    "@radix-ui/react-toast": ^1.2.11
    "@radix-ui/react-toggle": ^1.1.6
    "@radix-ui/react-toggle-group": ^1.1.7
    "@radix-ui/react-tooltip": ^1.2.4

  ##########################
  ## Tooling dependencies ##
  ##########################
  types:
    "@types/node": ^22.15.3
    "@types/react": ^19.1.2
    "@types/react-dom": ^19.1.3

  test:
    vitest: ^3.1.2
    vite-tsconfig-paths: ^5.1.4

  lint:
    "@biomejs/biome": 1.9.4
    "@commitlint/cli": ^19.8.0
    "@commitlint/config-conventional": ^19.8.0
    "@eslint/js": ^9.26.0
    "@next/eslint-plugin-next": ^15.3.1
    "@tanstack/eslint-plugin-query": ^5.74.7
    "@typescript-eslint/eslint-plugin": ^8.31.1
    "@typescript-eslint/parser": ^8.31.1
    eslint: ^9.26.0
    eslint-config-prettier: ^10.1.2
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-turbo: ^2.5.2
    lint-staged: ^15.5.1
    typescript-eslint: ^8.31.1

  devtools:
    "@turbo/gen": ^2.5.2
    changelogen: ^0.6.1
    eslint-plugin-pnpm: ^0.3.1
    globals: ^16.0.0
    husky: ^9.1.7
    taze: ^19.0.4
    turbo: ^2.5.2
    tsx: ^4.19.4
    typescript: ^5.8.3
