#!/usr/bin/env sh

echo "Running pre-commit hook"

###################################################################
# Format the staged files using lint-staged                       #
###################################################################
pnpm lint-staged
