name: Karr Release

on:
    push:
        tags:
            - v*

permissions:
    contents: read

env:
    TURBO_TELEMETRY_DISABLED: 1
    # You can leverage Vercel Remote Caching with Turbo to speed up your builds
    # @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    HUSKY: 0

jobs:
    checks:
        uses: ./.github/workflows/checks.yml
        secrets: inherit

    release:
        needs: checks
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        outputs:
            version: ${{ steps.package-version.outputs.current-version }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: get-npm-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.3.1

    #         - uses: pnpm/action-setup@v4
    #           name: Install pnpm
    #           with:
    #               run_install: false

    #         - name: Install Node.js
    #           uses: actions/setup-node@v4
    #           with:
    #               node-version: 22
    #               cache: "pnpm"

    #         - name: Install dependencies
    #           run: pnpm install

    #         - name: Create Release
    #           run: pnpm changeset tag
    #           env:
    #               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    build-api:
        needs: release
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Git Checkout
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: https://ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push API Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./apps/api/Dockerfile
                  push: true
                  tags: |
                      ghcr.io/karr-mobi/karr-api:latest
                      ghcr.io/karr-mobi/karr-api:${{ needs.release.outputs.version }}

    build-web:
        needs: release
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Git Checkout
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: https://ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Web Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./apps/web/Dockerfile
                  push: true
                  tags: |
                      ghcr.io/karr-mobi/karr-web:latest
                      ghcr.io/karr-mobi/karr-web:${{ needs.release.outputs.version }}

    build-caddy:
        needs: release
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Git Checkout
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: https://ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Container build will fail if the Caddyfile config is invalid
            - name: Build and push Caddy Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./apps/caddy
                  file: ./apps/caddy/Dockerfile
                  push: true
                  tags: |
                      ghcr.io/karr-mobi/karr-caddy:latest
                      ghcr.io/karr-mobi/karr-caddy:${{ needs.release.outputs.version }}
